### ISSUE TITLE
Consider Using ONNX For Common Model Runtime

### ISSUE THREAD

**Issue by John-P** [TIA-Lab/tiatoolbox#11]
I thought it sensible to make an issue to track the discussion around this. I recently suggested looking into using ONNX runtime for models as it would allow one cross-platform dependency for doing model inference instead of having to worry about both PyTorch and TensorFlow. It also looks as if training an ONNX model is also in beta (via PyTorch or TensorFlow).

**If anyone could try converting their model to ONNX and running it that would be good to get some feedback.**

**Some links for more information**

- ONNX Runtime GH: https://github.com/Microsoft/onnxruntime
- ONNX Runtime Homepage: https://microsoft.github.io/onnxruntime/index.html
- Convert TensorFlow to ONNX: https://github.com/onnx/tensorflow-onnx
- Convert PyTorch to ONNX: https://pytorch.org/docs/stable/onnx.html
- Convert Scikit-Learn to ONNX: https://github.com/onnx/sklearn-onnx
- NVIDIA TensorRT Model Optimiser for ONNX: https://developer.nvidia.com/tensorrt
- ONNX Tutorials: https://github.com/onnx/tutorials
- Azure Blog Post About ONNX Runtime Inference: https://azure.microsoft.com/en-us/blog/onnx-runtime-for-inferencing-machine-learning-models-now-in-preview/
- ONNX + PyTorch Accelerated Training: https://cloudblogs.microsoft.com/opensource/2020/05/19/announcing-support-for-accelerated-training-with-onnx-runtime/
- ONNX models can be converted to run on mobile ([ONNX to CoreML](https://pytorch.org/tutorials/advanced/ONNXLive.html#convert-the-onnx-models-to-coreml-models)) or in a web browser ([ONNX.js](https://github.com/Microsoft/onnxjs))!

**Comment by shaneahmed** [comment]
@vqdang Please can you report your findings here on HoVerNet.

**Comment by John-P** [comment]
On a related note, this other interesting Microsoft project called [Hummingbird](https://github.com/Microsoft/hummingbird) can covert scikit-learn models such as decision trees to a serialzied form which works with accelerated/optimised neural net frameworks e.g. PyTorch etc. Also useful as I have found serializing scikit-learn models can be a massive pain. It usually involves pickle and can run into all sorts of issues with un-pickleable objects and potential security issues (un-pickling can allow arbitrary code to run).

Microsoft Hummingbird GitHub: https://github.com/Microsoft/hummingbird

**Comment by John-P** [comment]
Also found another similar effort by Apache called TVM: https://tvm.apache.org/about. It looks like it compiles and optimizes a model (e.g. an ONNX/PyTorch/Tensorflow model) to a hardware backend e.g. Cuda/Metal/vulkan/WASM/javascript etc. It looks like it could be run without having the full stack of drivers and frameworks installed e.g. CuDNN etc. as it outputs "minimum deployable modules".

For more see this blog post about the initial release: https://tvm.apache.org/2017/08/17/tvm-release-announcement

**Comment by vqdang** [comment]
@shaneahmed , @John-P 
Preliminary testing with ONNX is done. Pytorch to ONNX is relative painless aside the hassle of setting up the runtime environment for ONNX. However, there are some important things as follow
1. CUDA backend of the source framework and ONNX runtime may not be the same
2. Operators in source backend may not have compatible version in ONNX or require higher version (and may be more unstable), such as tensordot (both pytorch and tensorflow has equivalent operator), or upsampling (even nearest may have issue).

I attach here the quantitative results as well as 1 output sample. These are obtained from DGX. Would be nice if we have someone volunteer for window :)
 
|     Platform      |  DICE  |  DQ       | SQ         | PQ       | AJI         |
|---------------- |--------|----------|----------|---------|----------|
| Linux-ONNX   | 0.8172 | 0.78702 | 0.76217 | 0.6003 | 0.61686 |
| Linux-Pytorch | 0.8172 | 0.78702 | 0.76217 | 0.6003 | 0.61686 |

- Linux ONNX
<a href="https://user-images.githubusercontent.com/24943262/86574718-279b0500-bf6e-11ea-99a7-69c9f599f71f.png"><img src="https://user-images.githubusercontent.com/24943262/86574718-279b0500-bf6e-11ea-99a7-69c9f599f71f.png" width="200" height="200"/></a>
- Linux Pytorch
<a href="https://user-images.githubusercontent.com/24943262/86574732-2b2e8c00-bf6e-11ea-9dea-2304a1e346f8.png"><img src="https://user-images.githubusercontent.com/24943262/86574732-2b2e8c00-bf6e-11ea-9dea-2304a1e346f8.png" width="200" height="200"/></a>

**Comment by John-P** [comment]
Thanks @vqdang, good to see it worked and got the same results!

I also just happened to stumble across another thing today which looks similar to Apache TVM. PyTorch has a library called [Glow](https://github.com/pytorch/glow) which can compile a model to machine code via first converting to ONNX. Doesn't appear to be as mature as the others. Also looks as if the machine code is tuned to run on the specific hardware it is compiled for. However, I thought I'd post it here to keep track of things that could help in this area.

**Comment by shaneahmed** [comment]
> @shaneahmed , @John-P
> Preliminary testing with ONNX is done. Pytorch to ONNX is relative painless aside the hassle of setting up the runtime environment for ONNX. However, there are some important things as follow
> 
> 1. CUDA backend of the source framework and ONNX runtime may not be the same
> 2. Operators in source backend may not have compatible version in ONNX or require higher version (and may be more unstable), such as tensordot (both pytorch and tensorflow has equivalent operator), or upsampling (even nearest may have issue).
> 
> I attach here the quantitative results as well as 1 output sample. These are obtained from DGX. Would be nice if we have someone volunteer for window :)
> 
> Platform	DICE	DQ	SQ	PQ	AJI
> Linux-ONNX	0.8172	0.78702	0.76217	0.6003	0.61686
> Linux-Pytorch	0.8172	0.78702	0.76217	0.6003	0.61686
> * Linux ONNX
>   <img alt="" width="200" height="200" src="https://user-images.githubusercontent.com/24943262/86574718-279b0500-bf6e-11ea-99a7-69c9f599f71f.png">
> * Linux Pytorch
>   <img alt="" width="200" height="200" src="https://user-images.githubusercontent.com/24943262/86574732-2b2e8c00-bf6e-11ea-9dea-2304a1e346f8.png">

Thanks Dang. 
I agree cuda version is the main issue. PyTorch uses customised CUDA whereas TensorFlow can rely on "original" CUDA binaries from Nvidia. conda environment might be a solution as we have seen before.  
Please can you also test this with TensorFlow? To start with you can take any example from TensorFlow examples e.g., mnsit.
