### ISSUE TITLE
get_wsireader method of wsireader class doesn't work for .tiff files

### ISSUE THREAD

**Issue by R-J96** [TIA-Lab/tiatoolbox#131]
* TIA Toolbox version: 0.6.0
* Python version: 3.7.8
* Operating System: Ubuntu 20.04

### Description

The get_wsireader method currently does not support .tiff files, errors with FileNotSupported. Can this be added as .tiff files are already supported in the OpenSlideWSIReader method?

### What I Did
Trying to read in a tiff file called ```wsi_file_name```:
```
wsi_reader_v1 = wsireader.get_wsireader(
                input_img=wsi_file_name)
```
Errors with the following:
```
FileNotSupported                          Traceback (most recent call last)
<ipython-input-4-027d95e28b58> in <module>
      1 wsi_reader_v1 = wsireader.get_wsireader(
----> 2                 input_img=wsi_file_name)
      3 print(type(wsi_reader_v1))

~/.conda/envs/tiatoolbox/lib/python3.7/site-packages/tiatoolbox-0.6.0-py3.7.egg/tiatoolbox/wsicore/wsireader.py in get_wsireader(input_img)
   1794 
   1795         else:
-> 1796             raise FileNotSupported("Filetype not supported.")
   1797     elif isinstance(input_img, np.ndarray):
   1798         wsi = VirtualWSIReader(input_img)

FileNotSupported: Filetype not supported.
```

While .tiff files can still be read in with the OpenSlideWSIReader method this means downstream methods in classes like the patchpredictor class will also error with this same message as they use this get_wsireader method.

**Comment by shaneahmed** [comment]
Working on it in PR #109 and #116
