### ISSUE TITLE
PyTest Missing from Conda Dev Requirements

### ISSUE THREAD

**Issue by John-P** [TIA-Lab/tiatoolbox#25]
* TIA Toolbox version: Current develop branch (https://github.com/TIA-Lab/tiatoolbox/tree/525fcb0504d10cdd78b1edd65cc9ac011e47bf4d)

### Description

PyTest is missing from the conda dev requirements file (https://github.com/TIA-Lab/tiatoolbox/blob/master/requirements.dev.conda.yml) and trying to run tests will fail. Even worse if you have pytest installed elsewhere can use that installation instead and confusingly fail to import modules.

**Comment by shaneahmed** [comment]
Fixed in this commit https://github.com/TIA-Lab/tiatoolbox/commit/e94ce76c0b3e752a4d929bbcd4483ef4c497f4a7
