### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by Srijay-lab** [TIA-Lab/tiatoolbox#81]
* TIA Toolbox version: 0.5.1
* Python version: NA
* Operating System: NA

Following points need to be amended in the documentation 

1. In section "Reading WSI Image Data", keyword for WSIReader function is "input_img" and not "input_path" as mentioned in https://tia-toolbox.readthedocs.io/en/latest/usage.html . Also there should be get_wsireader() instead of wsireader() in documentation. Updation is required in case if any of functionality is getting deprecated. 

3.  slide_param = wsi.info() causes error due to its property decorator but calling it without () works and its doc is also missing.

4.  In slide_thumbnail function,OpenSlideWSIReader is redundant, get_wsireader() is enough

5. Explore how we can include line gaps in sphinx docs. There need some gaps between description of slide_thumbnail() and get_wsireader() functions. 

6. Has got unexpected keyword argument tile_read_size_w and tile_read_size_h in function save_tiles()

7. In part “Functional” in “Accessing Metadata”, AttributeError: 'WSIMeta' object has no attribute 'file_name'. Replace file_name with file_path

8. There is () in import statement in example of class tiatoolbox.tools.stainnorm.CustomNormaliser. Same () for next few Stain normalizers needed to be removed. Add an example of stain_matrix (defining it and taking some value).

9.  Import statement spelling mistake staiextract instead of stainextract

10. Function name mistake but function performs as given in example of tiatoolbox.utils.misc.mpp2objective_power

11. Numpy import statement is missing but used as np in example of tiatoolbox.utils.transforms.background_composite

**Comment by shaneahmed** [comment]
@Srijay-lab  is this issue resolved now?

**Comment by Srijay-lab** [comment]
@shaneahmed From the above points, point numbers 1,6 and 10 are still reflecting in the document https://tia-toolbox.readthedocs.io/en/latest/usage.html . Rest issues are looking solved.

**Comment by shaneahmed** [comment]
Please can you create a PR to fix these issues?

**Comment by Srijay-lab** [comment]
Sure, I will make one.

**Comment by shaneahmed** [comment]
Fixed in this commit https://github.com/TIA-Lab/tiatoolbox/commit/fda5d4a7288cdc03d2731d4acdf30714db6819f0
